apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cilium-olm
  name: cilium-olm
  namespace: cilium
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cilium-olm
  template:
    metadata:
      labels:
        name: cilium-olm
    spec:
      containers:
        - command:
            - /usr/local/bin/helm-operator
            - run
            - --watches-file=watches.yaml
            - --enable-leader-election
            - --leader-election-id=cilium-olm
            - --zap-devel
            - --metrics-addr=localhost:8082
            - --health-probe-bind-address=localhost:8081
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELATED_IMAGE_CILIUM
              value: quay.io/cilium/cilium@sha256:e02744b4413824093d25a6fb35e2e418f7301e55825fa53a8e1943fe7e9e5aef
            - name: RELATED_IMAGE_HUBBLE_RELAY
              value: quay.io/cilium/hubble-relay@sha256:a1bca42ac2f9f934d7dc9311ecff5ff7012023830a63ba2980091abbfc148cbb
            - name: RELATED_IMAGE_CILIUM_OPERATOR
              value: quay.io/cilium/operator-generic@sha256:d77f3e1472725b3c28b5d88d6a49c7fcba3072c0c08a26e2e16c1e9139c96207
            - name: RELATED_IMAGE_PREFLIGHT
              value: quay.io/cilium/cilium@sha256:e02744b4413824093d25a6fb35e2e418f7301e55825fa53a8e1943fe7e9e5aef
            - name: RELATED_IMAGE_CLUSTERMESH
              value: quay.io/cilium/clustermesh-apiserver@sha256:466182b742140f1566926d28066943206a62e80114460b8a46de029395b82e47
            - name: RELATED_IMAGE_CERTGEN
              value: quay.io/cilium/certgen@sha256:2e0fc99ace29bbe5837718684920112a026bffc46f70efb38ea596c524e68819
            - name: RELATED_IMAGE_HUBBLE_UI_BE
              value: quay.io/cilium/hubble-ui-backend@sha256:46070270b8ffe7ac3f1794721be0b5a09f906dff3492f8a199a5f995db362d2a
            - name: RELATED_IMAGE_HUBBLE_UI_FE
              value: quay.io/cilium/hubble-ui@sha256:bbf8b041152041d3ef000d6074a8dd5d40ed910b5c0067f365b00e52e449d467
            - name: RELATED_IMAGE_ETCD_OPERATOR
              value: quay.io/cilium/cilium-etcd-operator@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc
            - name: RELATED_IMAGE_NODEINIT
              value: quay.io/cilium/startup-script@sha256:a1454ca1f93b69ecd2c43482c8e13dc418ae15e28a46009f5934300a20afbdba
            - name: RELATED_IMAGE_CLUSTERMESH_ETCD
              value: quay.io/coreos/etcd@sha256:a67fb152d4c53223e96e818420c37f11d05c2d92cf62c05ca5604066c37295e9
          image: registry.connect.redhat.com/isovalent/cilium-olm:5f2caabbd9809b3e9ff40674444eb25dbcb21fab-v1.13.5
          name: operator
          ports:
            - containerPort: 9443
              name: https
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      hostNetwork: true
      serviceAccount: cilium-olm
      terminationGracePeriodSeconds: 10
      tolerations:
        - operator: Exists
      volumes:
        - emptyDir: {}
          name: tmp
