apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cilium-olm
  name: cilium-olm
  namespace: cilium
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cilium-olm
  template:
    metadata:
      labels:
        name: cilium-olm
    spec:
      containers:
        - command:
            - /usr/local/bin/helm-operator
            - run
            - --watches-file=watches.yaml
            - --enable-leader-election
            - --leader-election-id=cilium-olm
            - --zap-devel
            - --metrics-addr=localhost:8082
            - --health-probe-bind-address=localhost:8081
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELATED_IMAGE_CILIUM
              value: quay.io/cilium/cilium@sha256:edc1d05ea1365c4a8f6ac6982247d5c145181704894bb698619c3827b6963a72
            - name: RELATED_IMAGE_HUBBLE_RELAY
              value: quay.io/cilium/hubble-relay@sha256:db30e85a7abc10589ce2a97d61ee18696a03dc5ea04d44b4d836d88bd75b59d8
            - name: RELATED_IMAGE_CILIUM_OPERATOR
              value: quay.io/cilium/operator-generic@sha256:e061de0a930534c7e3f8feda8330976367971238ccafff42659f104effd4b5f7
            - name: RELATED_IMAGE_PREFLIGHT
              value: quay.io/cilium/cilium@sha256:edc1d05ea1365c4a8f6ac6982247d5c145181704894bb698619c3827b6963a72
            - name: RELATED_IMAGE_CLUSTERMESH
              value: quay.io/cilium/clustermesh-apiserver@sha256:a7353669b1f7cb96cd600d98c7dd12e909d876843a7a272a1bc407e114ed225c
            - name: RELATED_IMAGE_CERTGEN
              value: quay.io/cilium/certgen@sha256:2e0fc99ace29bbe5837718684920112a026bffc46f70efb38ea596c524e68819
            - name: RELATED_IMAGE_HUBBLE_UI_BE
              value: quay.io/cilium/hubble-ui-backend@sha256:3f140b7765bff6bad1233e5a4a7672180611d6cfa96e37c402b3088cd5fa8e57
            - name: RELATED_IMAGE_HUBBLE_UI_FE
              value: quay.io/cilium/hubble-ui@sha256:a48a003e36afef7951b4a307206ce7dac8d0dd4c802dcee9ce9b66c3edbb3135
            - name: RELATED_IMAGE_ETCD_OPERATOR
              value: quay.io/cilium/cilium-etcd-operator@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc
            - name: RELATED_IMAGE_NODEINIT
              value: quay.io/cilium/startup-script@sha256:a1454ca1f93b69ecd2c43482c8e13dc418ae15e28a46009f5934300a20afbdba
            - name: RELATED_IMAGE_CLUSTERMESH_ETCD
              value: quay.io/coreos/etcd@sha256:a67fb152d4c53223e96e818420c37f11d05c2d92cf62c05ca5604066c37295e9
          image: registry.connect.redhat.com/isovalent/cilium-olm:389ce399edb426e3e3e7a9c4f437f9f33fc047c8-v1.14.1
          name: operator
          ports:
            - containerPort: 9443
              name: https
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      hostNetwork: true
      serviceAccount: cilium-olm
      terminationGracePeriodSeconds: 10
      tolerations:
        - operator: Exists
      volumes:
        - emptyDir: {}
          name: tmp
