apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cilium-olm
  name: cilium-olm
  namespace: cilium
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cilium-olm
  template:
    metadata:
      labels:
        name: cilium-olm
    spec:
      containers:
        - command:
            - /usr/local/bin/helm-operator
            - run
            - --watches-file=watches.yaml
            - --enable-leader-election
            - --leader-election-id=cilium-olm
            - --zap-devel
            - --metrics-addr=localhost:8082
            - --health-probe-bind-address=localhost:8081
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELATED_IMAGE_CILIUM
              value: quay.io/cilium/cilium@sha256:323e5762a2412e4f274c34ffb655d57b439d3c057ada48167f8aa038729c1661
            - name: RELATED_IMAGE_HUBBLE_RELAY
              value: quay.io/cilium/hubble-relay@sha256:4387d06a9c0089de6a27d815a9a475f539b2f9eaf6ec7d95d1670b502e18f7ea
            - name: RELATED_IMAGE_CILIUM_OPERATOR
              value: quay.io/cilium/operator-generic@sha256:17a1b1cbc38bcce00fd4d793c7b6ab630fdaaa464d53e05967625c7b7306730d
            - name: RELATED_IMAGE_PREFLIGHT
              value: quay.io/cilium/cilium@sha256:323e5762a2412e4f274c34ffb655d57b439d3c057ada48167f8aa038729c1661
            - name: RELATED_IMAGE_CLUSTERMESH
              value: quay.io/cilium/clustermesh-apiserver@sha256:7bf626ebaafeaf51870f9f5dc4d5127797da97ab5365405cccadb480dae900cf
            - name: RELATED_IMAGE_CERTGEN
              value: quay.io/cilium/certgen@sha256:f09fccb919d157fc0a83de20011738192a606250c0ee3238e3610b6cb06c0981
            - name: RELATED_IMAGE_HUBBLE_UI_BE
              value: quay.io/cilium/hubble-ui-backend@sha256:f88a73a120521eeafbcdbd908f517117f6557bf61e115847853fac371f0d774c
            - name: RELATED_IMAGE_HUBBLE_UI_FE
              value: quay.io/cilium/hubble-ui@sha256:e15af59a2ded739e420be82de6cbdd0ce22f8d3f00e3a10b3d2d2734e074a394
            - name: RELATED_IMAGE_ETCD_OPERATOR
              value: quay.io/cilium/cilium-etcd-operator@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc
            - name: RELATED_IMAGE_NODEINIT
              value: quay.io/cilium/startup-script@sha256:a1454ca1f93b69ecd2c43482c8e13dc418ae15e28a46009f5934300a20afbdba
            - name: RELATED_IMAGE_CLUSTERMESH_ETCD
              value: quay.io/coreos/etcd@sha256:a67fb152d4c53223e96e818420c37f11d05c2d92cf62c05ca5604066c37295e9
          image: registry.connect.redhat.com/isovalent/cilium-olm:3404b4961832b1623337c0653f631efb3d51a2d6-v1.12.17
          name: operator
          ports:
            - containerPort: 9443
              name: https
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      hostNetwork: true
      serviceAccount: cilium-olm
      terminationGracePeriodSeconds: 10
      tolerations:
        - operator: Exists
      volumes:
        - emptyDir: {}
          name: tmp
