name: PR
on:
  pull_request: {}

jobs:
  lint:
    if: github.repository == 'isovalent/olm-for-cilium' && github.event_name == 'pull_request'
    name: Lint Image Build Logic
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://quay.io/cilium/image-maker:9e2e7ad1a524cf714d491945e90fe650125cd60a
        name: Run make lint
        with:
          entrypoint: make
          args: lint
  set-version:
    runs-on: ubuntu-20.04
    needs: lint
    outputs:
      version: ${{ steps.set.outputs.VERSION }}
    steps:
      - id: set
        name: Set Version
        run: |
          version=$(echo ${{ github.head_ref }} | rev | cut -d '/' -f 1 | rev)
          if ! [[ $version =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              version=nothing
          fi
          echo "VERSION=${version}" >> $GITHUB_OUTPUT
  build-and-validate:
    if: needs.set-version.outputs.version != 'nothing'
    env:
      PREFLIGHT_VERSION: 1.2.1
      PFLT_DOCKERCONFIG: ~/.docker/config.json
      VERSION: ${{ needs.set-version.outputs.version }}
    name: Build Images and Validate Images
    runs-on: ubuntu-20.04
    needs: set-version
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c
      - name: Login to Quay.io
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ISOVALENT_DEV_USERNAME }}
          password: ${{ secrets.QUAY_ISOVALENT_DEV_PASSWORD }}
      - name: Push to Quay.io
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./operator/cilium.${{ env.VERSION }}/
          push: true
          tags: quay.io/isovalent-dev/cilium-olm-ci:${{ env.VERSION }}-${{ github.event.pull_request.head.sha }}
      - name: Install Preflight
        run: |
          curl -L -o preflight-linux-amd64 https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/${{ env.PREFLIGHT_VERSION }}/preflight-linux-amd64
          sha256sum --check .github_workflow_assets/preflight-linux-amd64.sha256sum
          sudo chmod +x preflight-linux-amd64
          sudo mv preflight-linux-amd64 /usr/local/bin/preflight
      - name: Run Preflight
        run: |
          preflight check container \
          --pyxis-api-token=${{ secrets.RHCP_PREFLIGHT_API_KEY }} \
          -d ~/.docker/config.json \
          --certification-project-id=5fbe31ec8b7d4976604cbde0 \
          quay.io/isovalent-dev/cilium-olm-ci:${{ env.VERSION }}-${{ github.event.pull_request.head.sha }}
